version: "3.7"

services:
  mcc:
    build:
      args:
        user: agger
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mcc
    user: 1000:1000
    container_name: mcc
    restart: unless-stopped
    working_dir: /var/www/mcc-be
    volumes:
      - ./www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - nginx
      - mcc-db
    networks:
      - gyala
    extra_hosts:
      - "cos_test:172.16.50.101"

  mcc-db:
    image: mysql:5.7
    container_name: mcc-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mcc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - gyala

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8181:80"
    depends_on:
      - mcc-db
    networks:
      - gyala

  nginx:
    image: nginx:alpine
    container_name: mcc-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ./www:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - gyala

  npm:
    image: node:14.18
    working_dir: /var/www/mcc-fe
    entrypoint: ["npm"]
    volumes:
      - ./www/:/var/www/
    networks:
      - gyala

  redis:
    image: redis:4.0
    container_name: app_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - gyala

  websockets:
    build:
      context: ./
      dockerfile: websockets.dockerfile
    container_name: mcc-websockets
    restart: unless-stopped
    working_dir: /var/www/mcc-be
    depends_on:
      - redis
    volumes:
      - ./www/mcc-be:/var/www/mcc-be
    ports:
      - "6001:6001"
    networks:
      - gyala

  supervisor:
    build:
      context: .
      dockerfile: ./supervisor/dockerfile
    container_name: supervisor
    depends_on:
      - nginx
      - mcc
    volumes:
      - ./www/mcc-be:/var/www/mcc-be
    networks:
      - gyala

  postgresql:
    container_name: gyala_keycloak_postgres_b
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=keycloak
    #    ports:
    #      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - gyala

  keycloak:
    container_name: gyala_keycloak_b
    image: docker.io/bitnami/keycloak:20
    environment:
      - KEYCLOAK_DATABASE_PASSWORD=admin
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=admin
    volumes:
      - ./keycloak_data:/var/keycloakdata
    ports:
      - "8282:8080"
    networks:
      - gyala
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local

networks:
  gyala:
    driver: bridge
